### ISSUE TITLE
obstacles detection.

### ISSUE THREAD

**Issue by g02200jeff** [makerspet/makerspet_loki#1]
When the robot meets an obstacle (smaller than lidar detection field), there are issues. 
Have you the project to add a bumper to detect it and stop the robot ?

**Comment by makers-pet** [comment]
@g02200jeff glad to hear that you seem to have progressed to driving the robot automatically.

About having bumpers - Loki does not have bumpers, but Snoopy, the 300mm robot model, does have bumpers and the associated sensors. Loki does not have bumpers mainly because Loki is smaller (200mm) and does not have enough room to accommodate Snoopy's bumper sensors. I 

Bumpers alone may not be sufficient to solve other navigation problems caused by LiDAR limitations - in particular mirrors. I will be adding an ultrasonic distance sensor to detect solid objects invisible to LiDAR.

As far as ROS2 support for bumpers and ultrasonic distance sensor, it is about 25% done and will be finished, I'd guess, by the end of this summer (2024).
